Story/q20-1
diging/quadriga-2.0 pull request #1
Opened 2020-10-21 17:33 UTC by coder-aakash994

Enable full simple-user capabilities

- user registration
- email password reset

2020-10-22 18:55 UTC, jdamerow commented
Seriously Aakash, please read our guidelines regarding GitHub naming!

2020-10-22 19:50 UTC, jdamerow commented
Please resolve conflicts. I've added something to the pom and also fixed the indentation. Please set the right indentation as described here: https://diging.atlassian.net/wiki/spaces/DIGING/pages/2057011201/Java+Code+Style

2020-10-26 18:51 UTC, jdamerow requested changes

2020-10-26 18:51 UTC, jdamerow commented on quadriga/pom.xml
> + 		<app.url></app.url>
please adjust indentation

2020-10-26 18:51 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/config/SimpleUsersConfig.java
> +	@Value("${email_user}")
indentaiton

2020-10-26 18:51 UTC, jdamerow commented on quadriga/src/main/webapp/WEB-INF/views/login.html
> +      <title>CORD19 Geo Explorer</title>
title

2020-10-26 18:51 UTC, jdamerow commented on quadriga/src/main/webapp/WEB-INF/views/password/change.html
> + <title>Authority Matcher</title>
title

2020-10-26 18:51 UTC, jdamerow commented on quadriga/src/main/webapp/WEB-INF/views/resetPassword.html
> +<title>Authority Matcher</title>
title

2020-10-26 18:51 UTC, jdamerow commented on quadriga/src/main/webapp/WEB-INF/views/resetRequestSent.html
> + <title>Authority Matcher</title>
title

2020-10-26 18:57 UTC, jdamerow commented
Make it so, Jenkins.

2020-10-26 19:18 UTC, jdamerow commented
Make it so, Jenkins.

2020-10-26 19:19 UTC, jdamerow commented
There is something weird going on with the password field. It only shows one character:
![image](https://user-images.githubusercontent.com/8881141/97218100-9b238500-179e-11eb-9bd6-03423bd54509.png)

2020-10-26 19:26 UTC, jdamerow commented
Make it so, Jenkins.

2020-10-27 15:23 UTC, jdamerow commented
The label fields should not look like input fields:
![image](https://user-images.githubusercontent.com/8881141/97322959-ae8a2b00-1846-11eb-8fa8-34ad1522bb09.png)
And the error message if the passwords don't match should be in a red alert box or something.

Also, let's remove the register icon in the menu. The "sign up" link on the login page should be enough for now.

2020-10-28 09:26 UTC, coder-aakash994 commented
I ran this on my local and checked in both safari and chrome but the input fields are not in search boxes. Can you recheck?
<img width="769" alt="image" src="https://user-images.githubusercontent.com/23230314/97417359-d324e800-18c4-11eb-94c7-2486dd0807d8.png">

2020-10-28 13:46 UTC, jdamerow commented
It's on the password reset page.

2020-10-28 16:59 UTC, merged