Story/q20 23
diging/quadriga-2.0 pull request #29
Opened 2022-07-18 17:23 UTC by MaulikLim

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x] I am not reformatting any files in the wrong format or without cause. 
- [x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [x] I have added Javadoc/documentation where appropriate
- [x] I have added test cases where appropriate
- [x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
(you can copy the ticket if it hasn't changed) 

[Q20-23] - Deleting of collections
  
## Anything else the reviewer needs to know?

Need to update existing collection entries in database with the new field.
`db.collection.updateMany({}, { $set: { "isArchived" : false } });`

2022-07-19 14:51 UTC, jdamerow requested changes

2022-07-19 14:51 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/core/service/impl/CollectionManagerImpl.java
> +            if (eventGraph != null) {
there needs to be a comment here why this check is done

2022-07-19 14:51 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/web/ListArchivedCollectionController.java
> +    @RequestMapping(value = "/auth/archived-collections", method = RequestMethod.GET)
should be `/auth/collections/archived`

2022-07-19 14:51 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/web/ListArchivedCollectionController.java
> +        sizeInt = Integer.parseInt(size);
there should be try/caches around the parsing so the variables are simply set to the default values if bogus values are passed.

2022-07-19 18:18 UTC, jdamerow requested changes

2022-07-19 18:18 UTC, jdamerow commented on quadriga/src/main/webapp/WEB-INF/views/auth/displayCollection.html
> +		<a th:if="${collection.isArchived()}" th:href="@{/auth/archived-collections}" class="btn btn-primary btn-sm">
I believe this link is wrong now?

2022-07-19 18:18 UTC, jdamerow commented on quadriga/src/main/webapp/WEB-INF/views/auth/showArchivedCollections.html
> +        <div action="#" th:action="@{/auth/archived-collections}" method="GET">
same here

2022-07-19 18:18 UTC, jdamerow commented on quadriga/src/main/webapp/WEB-INF/views/auth/showcollections.html
> +        <a th:href="@{/auth/archived-collections}">
and here

2022-07-19 18:33 UTC, MaulikLim commented on quadriga/src/main/webapp/WEB-INF/views/auth/showcollections.html
> +        <a th:href="@{/auth/archived-collections}">
fixed

2022-07-20 13:32 UTC, jdamerow commented
Make it so, Jenkins.

2022-07-20 14:22 UTC, jdamerow commented
There should be a message when deleting a collection with networks that the collection will be archived not deleted.

2023-02-16 17:02 UTC, jdamerow requested changes

2023-02-16 17:02 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/core/model/Collection.java
> +    private boolean isArchived;
variable name should be `archived`

2023-02-16 17:02 UTC, jdamerow commented on quadriga/src/test/java/edu/asu/diging/quadriga/core/service/impl/CollectionManagerImplTest.java
> +        managerToTest.deleteCollection(id.toString());
there need to be checks after this method is run to make sure it does what it's supposed to be doing.

2023-03-21 14:38 UTC, jdamerow requested changes

2023-03-21 14:38 UTC, jdamerow commented on quadriga/pom.xml
> +        <db.password></db.password>
this should not be changed (database url is ok, but the rest should stay the way it was)

2023-03-21 14:38 UTC, jdamerow commented on quadriga/pom.xml
> +        <conceptpower.id.endpoint></conceptpower.id.endpoint>
add a comment about leading/trailing slashes here (e.g. should it be `https://chps.asu.edu/conceptpower/rest/` or `https://chps.asu.edu/conceptpower/rest`?)

2023-03-21 14:38 UTC, jdamerow commented on quadriga/src/main/resources/log4j.xml
> +        <!-- <appender-ref ref="FILE" />-->
should not be commented out

2023-03-21 14:38 UTC, jdamerow commented on quadriga/src/test/java/edu/asu/diging/quadriga/core/service/impl/CollectionManagerImplTest.java
> +        }
I don't think you need this, just let it throw the exceptions and the tests will fail automatically.

2023-03-21 14:38 UTC, jdamerow commented on quadriga/src/test/java/edu/asu/diging/quadriga/core/service/impl/CollectionManagerImplTest.java
> +        }
when does the test pass though? There needs to be an assert statement.

2023-04-26 15:56 UTC, jdamerow requested changes

2023-04-26 15:56 UTC, jdamerow commented on quadriga/logs/quadriga2.log
Please do not commit this.

2023-04-26 15:56 UTC, jdamerow commented on quadriga/pom.xml
> +        <neo4j.database>quadriga2</neo4j.database>
please don't change this (database url above is fine as it would just set a sensible default, but this should not be changed).

2023-04-26 15:56 UTC, jdamerow commented on quadriga/pom.xml
> +        <citesphere.client.secret>1fef2d29-7d30-435e-9210-c56eb18131cf</citesphere.client.secret>
these are sensitive information and never be pushed to a public repo!

2023-04-26 15:56 UTC, jdamerow commented on quadriga/src/test/java/edu/asu/diging/quadriga/core/service/impl/CollectionManagerImplTest.java
> +        Collection response = new Collection();
if we change the code to do something to the collection after it was save, then this test will fail if you just return an empty collection object. Maybe just return `collection` in line 155?

2023-05-24 17:18 UTC, jdamerow requested changes

2023-05-24 17:18 UTC, jdamerow commented on quadriga/logs/quadriga2.log
should not be committed/pushed

2023-05-24 17:18 UTC, jdamerow commented on quadriga/pom.xml
> +        <db.password></db.password>
?

2023-05-24 17:18 UTC, jdamerow commented on quadriga/pom.xml
> +        <conceptpower.id.endpoint>https://chps.asu.edu/conceptpower/</conceptpower.id.endpoint>
this does not belong to this story, does it?

2023-05-24 17:18 UTC, jdamerow commented on quadriga/src/test/java/edu/asu/diging/quadriga/core/service/impl/CollectionManagerImplTest.java
> +        Collection response = new Collection();
is this still used?

2023-05-24 17:18 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/web/ListArchivedCollectionController.java
> +    private CollectionRepository collectionRepo;
controllers should not directly talk to the repositories; there should be a service layer in between.

2023-05-30 16:44 UTC, jdamerow requested changes
log file is still pushed.

2023-05-30 17:48 UTC, jdamerow commented
Make it so, Jenkins.

2023-05-30 18:15 UTC, jdamerow commented
Make it so, Jenkins.

2023-05-30 18:21 UTC, jdamerow commented
The collections do not show up (neither on the collections page, nor on the archived one). I ran the mongodb command to update the archived property.

2023-05-30 18:26 UTC, jdamerow commented
This is the current data:
```
{ "_id" : ObjectId("61f44cdd3e937c739b167ee9"), "name" : "First collection", "description" : "collection", "apps" : [ "xxx", "x", "xx" ], "_class" : "edu.asu.diging.quadriga.core.model.Collection", "isArchived" : false }
{ "_id" : ObjectId("62d80e7eb68e63665204a8b9"), "name" : "to be archived", "description" : "test", "creationTime" : "2022-07-20T14:17:34.034522Z", "isArchived" : false, "apps" : [ "xx" ], "_class" : "edu.asu.diging.quadriga.core.model.Collection" }
```

2023-05-30 21:07 UTC, ShivaniYerram commented
It's working for me, the variable name has changed to "archived" from "isArchived", your data shows "isArchived" maybe that is the issue.

2023-06-06 17:30 UTC, jdamerow commented
Make it so, Jenkins.

2023-06-06 18:58 UTC, merged