Story/q20 8
diging/quadriga-2.0 pull request #6
Opened 2021-04-28 22:28 UTC by coder-aakash994

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x ] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [ x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x ] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [ x] I am not reformatting any files in the wrong format or without cause. 
- [ x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [ x] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [ ] I have added Javadoc/documentation where appropriate
- [ ] I have added test cases where appropriate
- [ ] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
(you can copy the ticket if it hasn't changed) 

...Put description here...
Created a new endpoint to read Networks.
Designed a new java object for Network node and default mappings
Added jackson library and used mapper to convert json to java object
Persisted data in DB.

Pending:
Need review of object used to store Network. It is not a graph currently as it stores NodeData instead of adjacency list. 
Test cases and java doc pending
  
## Anything else the reviewer needs to know?

... describe here ...

2021-05-17 15:54 UTC, jdamerow requested changes

2021-05-17 15:54 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/api/v0/AddNetworkController.java
> +            return errorResponse;
This needs to return proper json

2021-05-17 15:54 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/api/v0/AddNetworkController.java
> +            e.printStackTrace();
needs proper exception handling

2021-05-17 15:54 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/api/v0/AddNetworkController.java
> +    @RequestMapping(value = "/rest/add", method = RequestMethod.POST)
url should be `/api/v1/network/add`

2021-05-17 15:54 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/api/v0/AddNetworkController.java
> +        return new ArrayList<>();
this should return something better than an empty list

2021-05-17 15:54 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/service/impl/NetworkCreationService.java
> +public class NetworkCreationService implements INetworkCreationService {
should be called `NetworkService`

2021-05-17 15:54 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/service/impl/RepositoryManager.java
> +   private INetworkCreationService elementDao;
name doesn't match classname

2021-05-17 15:54 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/service/impl/RepositoryManager.java
> +@Deprecated
should not be deprecated

2021-05-17 15:54 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/service/impl/RepositoryManager.java
> +        elementDao.saveElement(network);
the saved network needs to be returned (the value that `saveElement` returns)

2021-05-17 15:54 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/network/model/Network.java
> +public class Network {
the data model does not seem complete. Where is the information about the subject, predicate, objects? There are just ids, but it needs all the data.

2021-05-17 15:54 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/network/model/Network.java
> +    private NodeData defaultMapping;
why is the class NodeData but the variable name says `defaultMapping`?

2021-06-10 22:41 UTC, renuvarma commented
I have made changes to the network object.

2021-06-14 18:39 UTC, jdamerow requested changes
before I review any further please fix your eclipse format settings

2021-06-14 18:39 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/api/v0/AddNetworkController.java
> +        if (json.equals("")) {
I would trim `json` first.

2021-06-14 18:39 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/api/v0/AddNetworkController.java
> +            response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
since we use spring, let's use the spring enum here `HttpStatus`

2021-06-14 18:39 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/api/v0/AddNetworkController.java
> +            // request.").toString(accept));
remove if not needed

2021-06-14 18:39 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/api/v0/AddNetworkController.java
> +            e.printStackTrace();
?

2021-06-14 18:39 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/api/v0/AddNetworkController.java
> +        response.setStatus(HttpServletResponse.SC_OK);
see above

2021-06-14 18:39 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/api/v0/AddNetworkController.java
> +    private static final String JSON = "application/json";
use spring class instead `MediaType`

2021-06-14 18:39 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/config/SecurityContext.java
> +                        if (arg0.getRequestURI().indexOf("/rest/") > -1) {
is there an endpoint that has `/rest` in it?

2021-06-14 18:39 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/config/SecurityContext.java
> +                        "/reset/**", "/rest/**")
see above

2021-06-14 18:39 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/api/v0/AddNetworkController.java
> +    public int processJson(HttpServletRequest request, HttpServletResponse response, @RequestBody String json,
how is this endpoint currently secured?

2021-06-17 12:40 UTC, jdamerow requested changes
the new endpoint should store quadruples in the form of the existing quadruple model not networks; the network classes would represent the json format coming in but it needs to be mapped to the quadruple model and stored in mongo.

2021-06-17 12:40 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/api/v0/AddNetworkController.java
> +    	json.trim();
this doesn't do anything as strings are immutable.

2021-06-17 12:40 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/api/v0/AddNetworkController.java
> +            e.printStackTrace();
?

2021-06-17 12:40 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/config/SecurityContext.java
> +                        // don't require CSRF for REST calls
comment is inaccurate

2021-06-17 12:40 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/network/model/Network.java
> +    private DefaultMapping defaultMapping;
indentation

2021-06-17 12:40 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/network/model/NodeData.java
> +}
indentation

2021-06-17 12:40 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/service/impl/RepositoryManager.java
> +   private INetworkService networkService;
indentation

2021-06-22 22:06 UTC, renuvarma commented
Added Quadruple model class to stored it in mongo db

2021-07-08 20:20 UTC, closed without merging