Story/q20 5
diging/quadriga-2.0 pull request #8
Opened 2021-05-17 19:31 UTC by renuvarma

# Guidelines for Pull Requests

If you haven't yet read our code review guidelines, please do so, You can find them [here](https://diging.atlassian.net/wiki/spaces/DIGING/pages/2256076801/Code+Review+Guidelines).

Please confirm the following by adding an x for each item (turn `[ ]` into `[x]`).

- [x ] I have removed all code style changes that are not necessary (e.g. changing blanks across the whole file that don’t need to be changed, adding empty lines in parts other than your own code)
- [ x] I am not making any changes to files that don’t have any effect (e.g. imports added that don’t need to be added)
- [x ] I do not have any sysout statements in my code or commented out code that isn’t needed anymore
- [x ] I am not reformatting any files in the wrong format or without cause. 
- [ x] I am not changing file encoding or line endings to something else than UTF-8, LF
- [x ] My pull request does not show an insane amount of files being changed although my ticket only requires a few files being changed
- [ ] I have added Javadoc/documentation where appropriate
- [x ] I have added test cases where appropriate
- [ x] I have explained any part of my code/implementation decisions that is not be self-explanatory

## Please provide a brief description of your ticket 
(you can copy the ticket if it hasn't changed) 

[Q20-5] made additional changes according to the review comments and fixed the test case.
  
## Anything else the reviewer needs to know?

... describe here ...

2021-05-19 16:52 UTC, jdamerow requested changes

2021-05-19 16:52 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/service/impl/CollectionManager.java
> +     * @param collectionForm   Form data that needs to be added to database
this is incorrect

2021-05-19 16:52 UTC, jdamerow commented on quadriga/src/test/java/edu/asu/diging/quadriga/core/service/impl/CollectionManagerTest.java
> +        collection1.setName("name");
indentation

2021-05-19 16:53 UTC, jdamerow commented
- "I have added Javadoc/documentation where appropriate" should be checked.
- please reopen existing PRs next time

2021-05-19 16:53 UTC, jdamerow commented
Make it so, Jenkins.

2021-05-19 17:04 UTC, jdamerow commented
Let's also add a page that shows all collections. I will create new tickets for deleting/editing collections, but without an overview page that shows all collections it's hard to tell if something went wrong.

2021-05-20 22:01 UTC, renuvarma commented
Added the requested changes on indentation

2021-06-02 18:10 UTC, jdamerow commented
what about:
> Let's also add a page that shows all collections. I will create new tickets for deleting/editing collections, but without an overview page that shows all collections it's hard to tell if something went wrong.

2021-06-08 16:18 UTC, renuvarma commented
Added Show Collections page to show all the collections

2021-06-10 13:21 UTC, jdamerow requested changes

2021-06-10 13:21 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/web/AddCollectionController.java
> +    @RequestMapping(value="/auth/collections/showcollection",method=RequestMethod.GET)
this should just be `/auth/collections`

2021-06-10 13:21 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/web/AddCollectionController.java
> +        return "redirect:/auth/collections/add";
should redirect to the collections list page

2021-06-10 13:21 UTC, jdamerow commented on quadriga/src/main/webapp/WEB-INF/views/layouts/main.html
> +	          	</li>
this should be a drop down menu "Collections" with two menu items (See all and Add collection)

2021-06-10 13:21 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/web/AddCollectionController.java
> +    	return "showcollection";
the template should be in the same folder as the addcollection template

2021-06-10 19:09 UTC, renuvarma commented
Added the requested changes

2021-06-14 18:49 UTC, jdamerow requested changes

2021-06-14 18:49 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/web/AddCollectionController.java
> +    @RequestMapping(value="/auth/collections",method=RequestMethod.GET)
should be in its own controller

2021-06-14 18:49 UTC, jdamerow commented
Make it so, Jenkins.

2021-06-17 12:35 UTC, jdamerow requested changes

2021-06-17 12:35 UTC, jdamerow commented on quadriga/src/main/java/edu/asu/diging/quadriga/web/ShowCollectionController.java
> +		model.addAttribute("collections",collectionRepo.findAll());
let's paginate this (if there are 100 collections you don't want them all on one page).

2021-06-17 12:35 UTC, jdamerow commented on quadriga/src/main/webapp/WEB-INF/views/layouts/main.html
> +	          	<li sec:authorize="hasRole('USER')" role="presentation">
the drop down menu button shouldn't look like it's selected. It should have a white background like the others and only get a grey background on hover.

2021-07-07 20:56 UTC, jdamerow commented
Make it so, Jenkins.

2021-07-08 14:10 UTC, jdamerow commented
Make it so, Jenkins.

2021-07-08 15:04 UTC, merged